name: ECS Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development # TODO: 本番環境などの対応が必要
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-oidc-role
          aws-region: ap-northeast-1

      # Secrets Managerに秘匿情報を入れている場合
      - name: Get secrets from AWS Secrets Manager
        id: get-aws-secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            FROM_SECRETSMANAGER,portal
          parse-json-secrets: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ vars.AWS_ACCOUNT_ID }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        env:
          FROM_SECRETSMANAGER: ${{ env.FROM_SECRETSMANAGER }}
        with:
          context: .
          file: ./.ecs/app/Dockerfile
          build-args: |
            FROM_SECRETSMANAGER=${{ env.FROM_SECRETSMANAGER }}
          tags: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ vars.AWS_ECR_REPO }}:latest
          push: true

      - uses: kayac/ecspresso@v2
        with:
          version: v2.3.1
      - run: |
          ecspresso deploy --config ecspresso.yml
