name: SecretLint

on:
  pull_request:
    branches:
      - main

jobs:
  secretlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SecretLint
        run: |
          npm install secretlint @secretlint/secretlint-rule-preset-recommend

      - name: SecretLint
        run: npx secretlint ./src
